name: recipe_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.19.0

  #Hooks
  flutter_hooks: ^0.20.5

  #chached image
  cached_network_image: ^3.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  dio: ^5.4.1
  google_fonts: ^6.1.0
  go_router: ^13.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
